included:
  - Sources
  - DomainTests/Tests

excluded:
  - .build

line_length:
  warning: 140
  error: 200

type_body_length:
  warning: 400
  error: 550

file_length:
  warning: 550
  error: 800

identifier_name:
  min_length: 2
  excluded:
    - id

reporter: xcode
